name: CustomCommands
version: '1.0.0'
main: com.VintageGaming.customCommands.CustomCommands
api-version: '1.21'
authors: [ VintageGaming ]
description: Create Custom Commands!
softdepend:
  - Vault

commands:
  customcommands:
    description: Main command for the CustomCommands plugin.
    aliases: [custom, customc, ccommands, customcommand]
    permission: customcommands.admin

permissions:
  customcommands.admin:
    description: Permission to reload Plugin and Commands
    default: op